version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: cloud-optimizer-api-gateway
    ports:
      - "8000:8000"
    environment:
      - CLOUD_OPTIMIZER_SIMULATION=true
      - CLOUD_OPTIMIZER_FORCE_SIMULATION=true
      - CLOUD_COST_NORMALIZATION_SERVICE=http://cloud-cost-normalization:8001
    volumes:
      - ./api-gateway:/app
      - ./cloud_integrations.py:/app/cloud_integrations.py
      - ./mock_data:/app/mock_data
    restart: unless-stopped

  cloud-cost-normalization:
    build:
      context: .
      dockerfile: cloud-cost-normalization/Dockerfile
    container_name: cloud-optimizer-cost-normalization
    ports:
      - "8001:8001"
    environment:
      - CLOUD_OPTIMIZER_SIMULATION=true
      - CLOUD_OPTIMIZER_FORCE_SIMULATION=true
    volumes:
      - ./cloud-cost-normalization:/app
      - ./cloud_integrations.py:/app/cloud_integrations.py
      - ./mock_data:/app/mock_data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloud-optimizer-frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - cloud-cost-normalization
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_COST_URL=http://localhost:8001
    restart: unless-stopped

networks:
  default:
    name: cloud-optimizer-network
    driver: bridge
