global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'cost-normalizer'
    static_configs:
      - targets: ['cost-normalizer:8000']

  - job_name: 'network-manager'
    static_configs:
      - targets: ['network-manager:8000']

  - job_name: 'cost-optimizer'
    static_configs:
      - targets: ['cost-optimizer:8000']

  - job_name: 'resource-inventory'
    static_configs:
      - targets: ['resource-inventory:8000']

  - job_name: 'budget-manager'
    static_configs:
      - targets: ['budget-manager:8000']

  - job_name: 'cost-storage'
    static_configs:
      - targets: ['cost-storage:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

rule_files:
  - 'recording.rules.yml'
  - 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # AlertManager configuration would go here
          # - 'alertmanager:9093'
