"""GCP Cloud Billing client package."""

from importlib import metadata

from .client import GCPBillingClient
from .exceptions import (
    APIError,
    AuthenticationError,
    BigQueryError,
    BudgetError,
    CacheError,
    CloudStorageError,
    ConfigurationError,
    CredentialsError,
    DataNotFoundError,
    ExportError,
    InvalidBillingAccountError,
    InvalidFilterError,
    InvalidGroupingError,
    InvalidMetricError,
    InvalidTimeframeError,
    ProjectError,
    PubSubError,
    RateLimitError,
    ServiceError,
)
from .models import (
    BillingQueryDefinition,
    BillingQueryResult,
    BillingRow,
    BudgetAlertThreshold,
    BudgetAmount,
    BudgetDefinition,
    BudgetFilter,
    BudgetStatus,
    CostMetricType,
    CreateBudgetRequest,
    DeleteBudgetRequest,
    ExportDataRequest,
    ExportStatus,
    FilterType,
    GetBillingDataRequest,
    GetPricingRequest,
    GranularityType,
    GroupingDimension,
    ListBudgetsRequest,
    MetricConfiguration,
    MetricValue,
    PricingInfo,
    QueryDataset,
    QueryFilter,
    QueryGrouping,
    QueryTimeframe,
    ServiceInfo,
    ServiceType,
    SkuInfo,
    TimeframeType,
    UpdateBudgetRequest,
)

try:
    __version__ = metadata.version("gcp-billing-client")
except metadata.PackageNotFoundError:  # pragma: no cover
    __version__ = "0.1.0.dev0"

__all__ = [
    # Main client
    "GCPBillingClient",
    
    # Models
    "BillingQueryDefinition",
    "BillingQueryResult",
    "BillingRow",
    "BudgetAlertThreshold",
    "BudgetAmount",
    "BudgetDefinition",
    "BudgetFilter",
    "BudgetStatus",
    "CostMetricType",
    "CreateBudgetRequest",
    "DeleteBudgetRequest",
    "ExportDataRequest",
    "ExportStatus",
    "FilterType",
    "GetBillingDataRequest",
    "GetPricingRequest",
    "GranularityType",
    "GroupingDimension",
    "ListBudgetsRequest",
    "MetricConfiguration",
    "MetricValue",
    "PricingInfo",
    "QueryDataset",
    "QueryFilter",
    "QueryGrouping",
    "QueryTimeframe",
    "ServiceInfo",
    "ServiceType",
    "SkuInfo",
    "TimeframeType",
    "UpdateBudgetRequest",
    
    # Exceptions
    "APIError",
    "AuthenticationError",
    "BigQueryError",
    "BudgetError",
    "CacheError",
    "CloudStorageError",
    "ConfigurationError",
    "CredentialsError",
    "DataNotFoundError",
    "ExportError",
    "InvalidBillingAccountError",
    "InvalidFilterError",
    "InvalidGroupingError",
    "InvalidMetricError",
    "InvalidTimeframeError",
    "ProjectError",
    "PubSubError",
    "RateLimitError",
    "ServiceError",
]
